# Generated by Django 4.2.16 on 2026-01-24 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KafkaEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("gateway-logs", "Gateway Logs"),
                            ("raw-ingestion-topic", "Raw Ingestion"),
                            ("dlq-events", "Dead Letter Queue"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kafka Event",
                "verbose_name_plural": "Kafka Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "status"], name="kafka_servi_topic_a30874_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="kafka_servi_created_bcd4c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KafkaConsumerOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("partition", models.IntegerField()),
                ("consumer_group", models.CharField(max_length=255)),
                ("offset", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consumer Offset",
                "verbose_name_plural": "Consumer Offsets",
                "unique_together": {("topic", "partition", "consumer_group")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("uri", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request latency in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "consumer",
                    models.CharField(
                        blank=True,
                        help_text="Kong consumer username",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="Kong service name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Kong route name",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_size", models.IntegerField(blank=True, null=True)),
                ("response_size", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["uri"], name="kafka_servi_uri_aab025_idx"),
                    models.Index(
                        fields=["status_code"], name="kafka_servi_status__3d2c3c_idx"
                    ),
                    models.Index(
                        fields=["consumer"], name="kafka_servi_consume_815935_idx"
                    ),
                ],
            },
        ),
    ]
