"""
Django settings for brand_automator project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging as _logging
import os
import sys
from pathlib import Path
from decouple import config
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate with: python -c "from django.core.management.utils import \
# get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config("SECRET_KEY")  # No default - MUST be set in .env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# Railway private networking: allow this service's own private domain so
# that service-to-service callbacks (e.g. orchestrator → Django) are not
# rejected with 400 DisallowedHost.  We use RAILWAY_PRIVATE_DOMAIN
# (auto-set by Railway on every service) rather than a wildcard to avoid
# host-header attacks via forged *.railway.internal values.
_railway_private_domain = config("RAILWAY_PRIVATE_DOMAIN", default="")
if _railway_private_domain and _railway_private_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_private_domain)


# Application definition

# Temporarily disabled multi-tenancy for SQLite development
# SHARED_APPS = [
#     'django_tenants',  # mandatory
#     'tenants',  # our tenant app
#
#     # Django apps
#     'django.contrib.contenttypes',
#     'django.contrib.auth',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.admin',
#
#     # Third party apps
#     'rest_framework',
#     'rest_framework_simplejwt',
#     'corsheaders',
# ]

# TENANT_APPS = [
#     # Django apps that must be in each tenant
#     'django.contrib.contenttypes',
#     'django.contrib.auth',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#
#     # Third party apps
#     'rest_framework',
#     'rest_framework_simplejwt',
# ]

SHARED_APPS = [
    "daphne",  # ASGI server — must be before django.contrib.staticfiles
    "django_tenants",  # mandatory
    "tenants",  # our tenant app
    # Django apps
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_celery_beat",  # Celery periodic tasks
    # Our shared apps
    "ai_services",  # AI integration (shared for logging)
    "onboarding",  # Company data (has FK to Tenant)
    "subscriptions",  # Stripe payment integration
    "automation",  # Social media automation
    "kafka_service",  # Kafka consumer/producer service
    "data_ingestion",  # Data ingestion pipeline (Hexagonal Architecture)
    "media_curation",  # Media curation pipeline (Hexagonal Architecture)
    "rag_index",  # RAG Index sync service (Hexagonal Architecture)
    "orchestration",  # Pipeline orchestration (core-api-service)
    "workspace",  # Workflow management workspace
    "analytics",  # Workflow analytics layer
    "optimization",  # Campaign optimization (COA-3.4 background service)
    "intelligence_loop",  # Intelligence Loop Agent (ILA, WF3.5)
]

TENANT_APPS = [
    # Our apps
    "files",  # file management
    # Django apps that must be in each tenant
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    # CORS middleware - MUST BE FIRST for preflight OPTIONS requests
    # Note: When KONG_HANDLES_CORS=True, this can be removed
    "corsheaders.middleware.CorsMiddleware",
    # Multi-tenancy middleware - DefaultTenantMiddleware falls back to public schema
    "django_tenants.middleware.default.DefaultTenantMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise for static files - must be after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Kong Authentication Middleware - handles JWT from Kong Gateway
    # This should be after AuthenticationMiddleware to override when Kong is enabled
    "brand_automator.middleware.KongAuthenticationMiddleware",
    # Tenant Membership Middleware - resolves tenant from X-Tenant-ID header
    # and verifies user has active membership; must be after auth middleware
    "brand_automator.middleware.TenantMembershipMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom security middleware
    "brand_automator.middleware.SecurityMiddleware",
    "brand_automator.middleware.RequestValidationMiddleware",
    # Rate limiting disabled when Kong handles it
    "brand_automator.middleware.RateLimitMiddleware",
]

ROOT_URLCONF = "brand_automator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "brand_automator.wsgi.application"
ASGI_APPLICATION = "brand_automator.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
_db_log = _logging.getLogger(__name__)

# Determine if we're in test mode
TESTING = "pytest" in sys.modules or "test" in sys.argv


def _sanitize_url(raw: str) -> str:
    """Strip whitespace, quotes, newlines, null bytes, and BOM from a URL.

    Railway/Neon dashboard copy-paste can inject invisible characters
    or surrounding quotes that break urllib.parse.urlsplit().
    """
    if not raw:
        return ""
    # Remove BOM, null bytes, carriage returns, and all whitespace
    cleaned = raw.strip().replace("\ufeff", "").replace("\x00", "")
    # Remove any newlines or tabs that might be embedded
    cleaned = "".join(ch for ch in cleaned if ch not in "\n\r\t")
    # Strip surrounding quotes (single or double) from copy-paste errors
    if len(cleaned) >= 2 and cleaned[0] == cleaned[-1] and cleaned[0] in "\"'":
        cleaned = cleaned[1:-1]
    return cleaned


# Database configuration — reads from os.environ DIRECTLY to avoid any
# python-decouple interference (decouple may read stale .env files when
# os.environ has the value but with invisible characters).
# This is the ONE exception to the "never os.environ" rule because
# DATABASE_URL parsing in prod is critical and hard to debug.
_raw_db_url = os.environ.get("DATABASE_URL", "")
DATABASE_URL = _sanitize_url(_raw_db_url)
_db_url_source = "DATABASE_URL"

# Log what we found for debugging Railway deployments
if _raw_db_url:
    _db_log.info(
        "DATABASE_URL from os.environ: len=%d, first_20=%r, sanitized_len=%d",
        len(_raw_db_url),
        _raw_db_url[:20],
        len(DATABASE_URL),
    )
else:
    _db_log.info("DATABASE_URL not in os.environ, trying decouple + alternatives")
    # Fall back to decouple for local dev (reads .env file)
    DATABASE_URL = config("DATABASE_URL", default="").strip()

# If DATABASE_URL is empty, try alternative variable names used by
# Railway, Render, and other PaaS platforms.
if not DATABASE_URL:
    _DB_URL_ALTERNATIVES = (
        "DATABASE_PRIVATE_URL",
        "DATABASE_PUBLIC_URL",
        "POSTGRES_URL",
        "POSTGRESQL_URL",
    )
    for _alt_name in _DB_URL_ALTERNATIVES:
        _alt_url = _sanitize_url(os.environ.get(_alt_name, ""))
        if not _alt_url:
            _alt_url = config(_alt_name, default="").strip()
        if _alt_url:
            DATABASE_URL = _alt_url
            _db_url_source = _alt_name
            _db_log.info("Using %s (DATABASE_URL was empty)", _alt_name)
            break

# Validate DATABASE_URL has a real scheme (not empty or whitespace-only).
# Use find("://") > 0 to reject edge cases like "://bad" (no scheme).
_db_url_valid = bool(DATABASE_URL) and DATABASE_URL.find("://") > 0

if _db_url_valid:
    # Use DATABASE_URL if available (Railway, Heroku, etc.)
    # Use parse() with the explicit value to avoid dj_database_url
    # re-reading os.environ["DATABASE_URL"] independently.
    try:
        DATABASES = {
            "default": dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
        # Set engine for django-tenants
        DATABASES["default"]["ENGINE"] = "django_tenants.postgresql_backend"
        _db_log.info(
            "Database configured via %s (scheme: %s)",
            _db_url_source,
            DATABASE_URL.split("://")[0],
        )
    except Exception as exc:
        # dj_database_url can raise ValueError, KeyError, or
        # django.core.exceptions.ImproperlyConfigured for invalid URLs.
        _db_log.error(
            "Failed to parse %s: %s. Falling back to individual DB_* vars.",
            _db_url_source,
            exc,
        )
        _db_url_valid = False

if not _db_url_valid:
    # Fall back to individual DB_* variables (local development or
    # Railway with individual vars set instead of DATABASE_URL).
    # Read each var once with its real default to avoid redundant config() calls.
    _db_name = config("DB_NAME", default="neondb")
    _db_user = config("DB_USER", default="neondb_owner")
    _db_password = config("DB_PASSWORD", default="")
    _db_host = config("DB_HOST", default="localhost")
    _db_port = config("DB_PORT", default="5432")
    _db_sslmode = config("DB_SSLMODE", default="require")
    _db_channel_binding = config("DB_CHANNEL_BINDING", default="require")

    if _db_host == "localhost" and not DEBUG:
        _db_log.critical(
            "No database configured! Set DATABASE_URL or individual "
            "DB_HOST/DB_NAME/DB_USER/DB_PASSWORD environment variables. "
            "The app will fail to connect."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django_tenants.postgresql_backend",
            "NAME": _db_name,
            "USER": _db_user,
            "PASSWORD": _db_password,
            "HOST": _db_host,
            "PORT": _db_port,
            "OPTIONS": {
                "sslmode": _db_sslmode,
                "channel_binding": _db_channel_binding,
            },
        }
    }
    _db_log.info(
        "Database configured via individual DB_* vars (host: %s)",
        _db_host,
    )

# Multi-tenancy settings
DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)
TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"
# Show public schema if no tenant found (allows health checks on unknown domains)
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

# Custom User Model - temporarily disabled for migration
# AUTH_USER_MODEL = 'tenants.User'

# CORS settings
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:3001,http://localhost:3002"
    ),
    cast=lambda v: [s.strip() for s in v.split(",")],
)
# Note: Add development IPs to CORS_ALLOWED_ORIGINS env var instead of using
# CORS_ALLOW_ALL_ORIGINS for security. Example:
# CORS_ALLOWED_ORIGINS=http://localhost:3000,http://10.0.0.224:3000
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-tenant-id",
]

# =============================================================================
# Kong Gateway Integration Settings
# =============================================================================
# When KONG_ENABLED=True, Django trusts that Kong Gateway has already
# validated JWT tokens. The KongAuthenticationMiddleware will decode
# tokens without verification and extract user claims.
KONG_ENABLED = config("KONG_ENABLED", default=False, cast=bool)

# Trust proxy headers from Kong
# These headers are set by Kong when forwarding requests
USE_X_FORWARDED_HOST = config("USE_X_FORWARDED_HOST", default=KONG_ENABLED, cast=bool)
USE_X_FORWARDED_PORT = config("USE_X_FORWARDED_PORT", default=KONG_ENABLED, cast=bool)

# Secure proxy SSL header - trust X-Forwarded-Proto from Kong
# Format: (header_name, expected_value)
if KONG_ENABLED:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# When Kong handles CORS, we can disable Django CORS middleware
# Set KONG_HANDLES_CORS=True in production when Kong is the entry point
KONG_HANDLES_CORS = config("KONG_HANDLES_CORS", default=False, cast=bool)

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.PageNumberPagination"),
    "PAGE_SIZE": 20,
    "DEFAULT_VERSIONING_CLASS": ("rest_framework.versioning.NamespaceVersioning"),
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
}

# JWT settings
# These settings are used by both Django SimpleJWT and Kong Gateway
# The SIGNING_KEY must match the Kong JWT consumer secret

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    # Issuer claim - must match Kong JWT consumer key
    "ISSUER": config("JWT_ISSUER", default="ai-brand-automator"),
    # Audience claim (optional)
    "AUDIENCE": config("JWT_AUDIENCE", default=None),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise for static file serving in production
# Use simple storage to avoid manifest issues during collectstatic
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Google Cloud Storage settings
GS_BUCKET_NAME = config("GS_BUCKET_NAME", default="zorven-raw-assets")
GS_PROJECT_ID = config("GS_PROJECT_ID", default="zorven-503517")
GS_CREDENTIALS_PATH = config("GS_CREDENTIALS_PATH", default="")

# AI Service settings
GOOGLE_API_KEY = config("GOOGLE_API_KEY", default="")

# Email Configuration
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@brandautomator.com")

# CSRF Configuration
CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# Session Configuration
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# Security Headers (production)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # SECURE_SSL_REDIRECT disabled - Railway handles HTTPS at load balancer level
    # This also allows Railway's internal healthcheck (which uses HTTP) to work
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "errors.log",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "ai_services": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "onboarding": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "brand_automator": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Create logs directory if it doesn't exist

logs_dir = BASE_DIR / "logs"
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Stripe Configuration
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_PRICE_BASIC = config("STRIPE_PRICE_BASIC", default="")
STRIPE_PRICE_PRO = config("STRIPE_PRICE_PRO", default="")
STRIPE_PRICE_ENTERPRISE = config("STRIPE_PRICE_ENTERPRISE", default="")

# LinkedIn OAuth Configuration
LINKEDIN_CLIENT_ID = config("LINKEDIN_CLIENT_ID", default="")
LINKEDIN_CLIENT_SECRET = config("LINKEDIN_CLIENT_SECRET", default="")
LINKEDIN_REDIRECT_URI = config(
    "LINKEDIN_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/linkedin/callback/",
)

# Twitter/X OAuth 2.0 Configuration
TWITTER_CLIENT_ID = config("TWITTER_CLIENT_ID", default="")
TWITTER_CLIENT_SECRET = config("TWITTER_CLIENT_SECRET", default="")
TWITTER_REDIRECT_URI = config(
    "TWITTER_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/twitter/callback/",
)

# Facebook OAuth 2.0 Configuration
FACEBOOK_APP_ID = config("FACEBOOK_APP_ID", default="")
FACEBOOK_APP_SECRET = config("FACEBOOK_APP_SECRET", default="")
FACEBOOK_REDIRECT_URI = config(
    "FACEBOOK_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/facebook/callback/",
)
# Facebook Webhook Configuration
# Set this to a random string and use the same value in Facebook Developer Portal
FACEBOOK_WEBHOOK_VERIFY_TOKEN = config("FACEBOOK_WEBHOOK_VERIFY_TOKEN", default="")

# Instagram OAuth 2.0 Configuration (via Facebook Graph API)
# Instagram Business accounts require a linked Facebook Page
INSTAGRAM_APP_ID = config("INSTAGRAM_APP_ID", default="")
INSTAGRAM_APP_SECRET = config("INSTAGRAM_APP_SECRET", default="")
INSTAGRAM_REDIRECT_URI = config(
    "INSTAGRAM_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/instagram/callback/",
)
# Instagram Webhook Configuration
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = config("INSTAGRAM_WEBHOOK_VERIFY_TOKEN", default="")

# Instagram Threads OAuth 2.0 Configuration (separate app)
INSTAGRAM_THREADS_APP_ID = config("INSTAGRAM_THREADS_APP_ID", default="")
INSTAGRAM_THREADS_APP_SECRET = config("INSTAGRAM_THREADS_APP_SECRET", default="")
INSTAGRAM_THREADS_REDIRECT_URI = config(
    "INSTAGRAM_THREADS_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/threads/callback/",
)

# Google Business Profile OAuth 2.0 Configuration
GOOGLE_BUSINESS_CLIENT_ID = config("GOOGLE_BUSINESS_CLIENT_ID", default="")
GOOGLE_BUSINESS_CLIENT_SECRET = config("GOOGLE_BUSINESS_CLIENT_SECRET", default="")
GOOGLE_BUSINESS_REDIRECT_URI = config(
    "GOOGLE_BUSINESS_REDIRECT_URI",
    default="http://localhost:8000/api/v1/automation/google-business/callback/",
)

# Frontend URL for OAuth redirects
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

# =============================================================================
# Kafka Configuration
# =============================================================================
KAFKA_BOOTSTRAP_SERVERS = config("KAFKA_BOOTSTRAP_SERVERS", default="localhost:9092")
KAFKA_CONSUMER_GROUP_ID = config(
    "KAFKA_CONSUMER_GROUP_ID", default="brand-automator-consumers"
)
KAFKA_AUTO_OFFSET_RESET = config("KAFKA_AUTO_OFFSET_RESET", default="earliest")
KAFKA_ENABLE_AUTO_COMMIT = config("KAFKA_ENABLE_AUTO_COMMIT", default=True, cast=bool)
KAFKA_SESSION_TIMEOUT_MS = config("KAFKA_SESSION_TIMEOUT_MS", default=30000, cast=int)

# Kafka SASL/SSL Authentication (for managed Kafka: Confluent Cloud, Upstash, etc.)
KAFKA_SECURITY_PROTOCOL = config("KAFKA_SECURITY_PROTOCOL", default="")
KAFKA_SASL_MECHANISM = config("KAFKA_SASL_MECHANISM", default="PLAIN")
KAFKA_SASL_USERNAME = config("KAFKA_SASL_USERNAME", default="")
KAFKA_SASL_PASSWORD = config("KAFKA_SASL_PASSWORD", default="")

# Kafka Topics
KAFKA_TOPIC_GATEWAY_LOGS = "gateway-logs"
KAFKA_TOPIC_RAW_INGESTION = "raw-ingestion-topic"
KAFKA_TOPIC_DLQ = "dlq-events"

# Build SASL/SSL config dict for confluent-kafka Producer/Consumer.
# Empty dict when KAFKA_SECURITY_PROTOCOL is not set (local dev).
KAFKA_SASL_CONFIG = (
    {
        "security.protocol": KAFKA_SECURITY_PROTOCOL,
        "sasl.mechanism": KAFKA_SASL_MECHANISM,
        "sasl.username": KAFKA_SASL_USERNAME,
        "sasl.password": KAFKA_SASL_PASSWORD,
    }
    if KAFKA_SECURITY_PROTOCOL
    else {}
)

# =============================================================================
# Orchestration Kafka Integration
# =============================================================================
# Enable Kafka-based dispatch (vs HTTP) and Kafka consumers for results/traces.
# When False, the existing HTTP dispatch + HTTP callback flow is used.
ORCHESTRATION_KAFKA_ENABLED = config(
    "ORCHESTRATION_KAFKA_ENABLED", default=False, cast=bool
)
KAFKA_TOPIC_PIPELINE_TRIGGER = "pipeline-trigger-topic"
KAFKA_TOPIC_AGENT_TRACE = "agent-trace-topic"
KAFKA_TOPIC_PIPELINE_RESULT = "pipeline-result-topic"
KAFKA_TOPIC_ORCHESTRATION_DLQ = "orchestration-dlq"
ORCHESTRATION_KAFKA_GROUP_ID = "orchestration-result-consumers"

# Analytics Kafka events — conditionally enabled
ANALYTICS_KAFKA_ENABLED = config("ANALYTICS_KAFKA_ENABLED", default=False, cast=bool)

# =============================================================================
# Data Ingestion Configuration (Hexagonal Architecture Pipeline)
# =============================================================================
DATA_INGESTION = {
    # Kafka Topics for ingestion pipeline
    "KAFKA_INPUT_TOPIC": config(
        "INGESTION_KAFKA_INPUT_TOPIC", default="raw-ingestion-topic"
    ),
    "KAFKA_OUTPUT_TOPIC": config(
        "INGESTION_KAFKA_OUTPUT_TOPIC", default="curation-needed-topic"
    ),
    "KAFKA_DLQ_TOPIC": config("INGESTION_KAFKA_DLQ_TOPIC", default="ingestion-dlq"),
    "KAFKA_GROUP_ID": config("INGESTION_KAFKA_GROUP_ID", default="ingestion-svc-group"),
    # GCS Configuration
    "GCP_PROJECT_ID": config("GCP_PROJECT_ID", default="zorven-503517"),
    "GCP_BUCKET_NAME": config("GCP_BUCKET_NAME", default="zorven-raw-assets"),
    "GCS_LANDING_PREFIX": config("GCS_LANDING_PREFIX", default="_landing"),
    "GCS_CREDENTIALS_PATH": config(
        "GOOGLE_APPLICATION_CREDENTIALS",
        default="",
    ),
    # Processing Configuration
    "MAX_RETRIES": config("INGESTION_MAX_RETRIES", default=3, cast=int),
    "RETRY_BACKOFF_SECONDS": config("INGESTION_RETRY_BACKOFF", default=1.0, cast=float),
    "DEDUPE_TTL_SECONDS": config("INGESTION_DEDUPE_TTL", default=3600, cast=int),
    "STATUS_TTL_SECONDS": config(
        "INGESTION_STATUS_TTL", default=604800, cast=int
    ),  # 7 days
    # RAG sync topic (for company documents)
    "KAFKA_RAG_TOPIC": config(
        "INGESTION_KAFKA_RAG_TOPIC", default="rag-sync-ready-topic"
    ),
}

# =============================================================================
# Vertex AI Search / RAG Index Configuration
# =============================================================================
VERTEX_AI_PROJECT_ID = config("VERTEX_AI_PROJECT_ID", default="zorven-503517")
VERTEX_AI_LOCATION = config("VERTEX_AI_LOCATION", default="global")
VERTEX_AI_DATA_STORE_ID = config("VERTEX_AI_DATA_STORE_ID", default="prevision-rag-dev")
VERTEX_AI_AUTO_PROVISION = config("VERTEX_AI_AUTO_PROVISION", default=False, cast=bool)
RAG_INDEX_MOCK_MODE = config("VERTEX_AI_MOCK_MODE", default=False, cast=bool)
GCP_PROJECT_ID = config("GCP_PROJECT_ID", default="zorven-503517")
GCP_LOCATION = config("GCP_LOCATION", default="global")

# --- DB-to-RAG Sync ---
RAG_DB_SYNC_ENABLED = config("RAG_DB_SYNC_ENABLED", default=False, cast=bool)
RAG_DB_SYNC_PERIODIC_INTERVAL = config(
    "RAG_DB_SYNC_PERIODIC_INTERVAL", default=1800, cast=int
)  # 30 min
RAG_DB_SYNC_MODELS = config(
    "RAG_DB_SYNC_MODELS",
    default="Company,AnalysisJob,ChatMessage,AIGeneration,ContentCalendar",
)

# =============================================================================
# Onboarding Pipeline Integration
# =============================================================================
# Enable/disable Kafka publishing from onboarding (set False for testing)
ONBOARDING_KAFKA_ENABLED = config("ONBOARDING_KAFKA_ENABLED", default=True, cast=bool)

# Webhook secret for pipeline status callbacks (optional, but recommended)
# When set, webhooks must include X-Pipeline-Secret header or secret param
PIPELINE_WEBHOOK_SECRET = config("PIPELINE_WEBHOOK_SECRET", default="")

# =============================================================================
# Media Curation Configuration (Hexagonal Architecture Pipeline)
# =============================================================================
MEDIA_CURATION = {
    # Kafka Topics for curation pipeline
    "KAFKA": {
        "BOOTSTRAP_SERVERS": KAFKA_BOOTSTRAP_SERVERS,
        "INPUT_TOPIC": config(
            "CURATION_KAFKA_INPUT_TOPIC", default="curation-needed-topic"
        ),
        "OUTPUT_TOPIC": config(
            "CURATION_KAFKA_OUTPUT_TOPIC", default="rag-sync-ready-topic"
        ),
        "DLQ_TOPIC": config("CURATION_KAFKA_DLQ_TOPIC", default="curation-dlq"),
        "GROUP_ID": config("CURATION_KAFKA_GROUP_ID", default="curation-svc-group"),
    },
    # Storage Configuration (GCS)
    "STORAGE": {
        "GCP_PROJECT_ID": config("GCP_PROJECT_ID", default="zorven-503517"),
        "CURATED_BUCKET": config(
            "CURATION_GCP_BUCKET_NAME", default="zorven-curated-assets"
        ),
        "RAW_BUCKET": config("RAW_GCP_BUCKET_NAME", default="zorven-raw-assets"),
        "CREDENTIALS_PATH": config(
            "GOOGLE_APPLICATION_CREDENTIALS",
            default="",
        ),
    },
    # DLP Configuration (Google Cloud DLP)
    "DLP": {
        "ENABLED": config("CURATION_DLP_ENABLED", default=True, cast=bool),
        "GCP_PROJECT_ID": config("DLP_GCP_PROJECT_ID", default="zorven-503517"),
        "INFO_TYPES": config(
            "DLP_INFO_TYPES",
            default=(
                "PHONE_NUMBER,EMAIL_ADDRESS,PERSON_NAME,"
                "STREET_ADDRESS,CREDIT_CARD_NUMBER"
            ),
            cast=lambda v: [s.strip() for s in v.split(",")],
        ),
        "REDACTION_STRATEGY": config(
            "DLP_REDACTION_STRATEGY", default="REPLACE"
        ),  # REPLACE, MASK, HASH
    },
    # AI Model Configuration (Gemini)
    "AI_MODEL": {
        "PROVIDER": config("CURATION_AI_PROVIDER", default="gemini"),
        "MODEL_NAME": config("CURATION_AI_MODEL", default="gemini-2.0-flash"),
        "MAX_TOKENS": config("CURATION_AI_MAX_TOKENS", default=8192, cast=int),
        "TEMPERATURE": config("CURATION_AI_TEMPERATURE", default=0.1, cast=float),
    },
    # Processing Configuration
    "PROCESSING": {
        "MAX_RETRIES": config("CURATION_MAX_RETRIES", default=3, cast=int),
        "RETRY_BACKOFF_SECONDS": config(
            "CURATION_RETRY_BACKOFF", default=1.0, cast=float
        ),
        "BATCH_SIZE": config("CURATION_BATCH_SIZE", default=10, cast=int),
        "POLL_TIMEOUT_SECONDS": config(
            "CURATION_POLL_TIMEOUT", default=1.0, cast=float
        ),
    },
    # Cache Configuration (Redis)
    "CACHE": {
        "STATUS_TTL_SECONDS": config(
            "CURATION_STATUS_TTL", default=604800, cast=int
        ),  # 7 days
        "DEDUPE_TTL_SECONDS": config("CURATION_DEDUPE_TTL", default=3600, cast=int),
        "KEY_PREFIX": "curation:",
    },
}

# =============================================================================
# Django Cache Configuration (Redis)
# =============================================================================
REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/1")

if "pytest" in sys.modules:
    # Use in-memory cache during tests to avoid requiring Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "KEY_PREFIX": "ba:",
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "ba:",
            "TIMEOUT": 300,  # 5 minutes default
        }
    }

# =============================================================================
# Django Channels (WebSocket) Configuration
# =============================================================================
CHANNELS_REDIS_URL = config("CHANNELS_REDIS_URL", default="redis://localhost:6379/0")

if "pytest" in sys.modules:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNELS_REDIS_URL],
            },
        }
    }

# =============================================================================
# Celery Configuration
# =============================================================================
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://localhost:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Celery Beat Configuration (for periodic tasks)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BEAT_SCHEDULE = {
    "publish-scheduled-posts": {
        "task": "automation.publish_scheduled_posts",
        # 1-minute interval allows posts to be published within ~1 min of
        # scheduled time. Trade-off: slight DB overhead vs user expectation
        # of timely delivery. For lower frequency, change to 300.0 (5 min).
        "schedule": 60.0,
    },
    "check-stale-orchestration-jobs": {
        "task": "orchestration.tasks.check_stale_jobs",
        "schedule": 300.0,  # Every 5 minutes
    },
}

# Explicit flag to enable Kafka consumer Celery tasks.
# Set to True when a Kafka broker is available (managed or local).
KAFKA_CONSUMERS_ENABLED = config("KAFKA_CONSUMERS_ENABLED", default=False, cast=bool)

# Kafka consumer tasks — only register when explicitly enabled
# (prevents error-flooding logs when no Kafka broker is available)
if KAFKA_CONSUMERS_ENABLED:
    CELERY_BEAT_SCHEDULE.update(
        {
            "consume-gateway-logs-every-minute": {
                "task": "kafka_service.tasks.consume_gateway_logs",
                "schedule": 60.0,
                "kwargs": {"max_messages": 100},
            },
            "consume-raw-events-every-30s": {
                "task": "kafka_service.tasks.consume_raw_events",
                "schedule": 30.0,
                "kwargs": {"max_messages": 50},
            },
            "process-dlq-every-5-minutes": {
                "task": "kafka_service.tasks.process_dlq_events",
                "schedule": 300.0,
                "kwargs": {"max_messages": 20},
            },
        }
    )

# Orchestration Kafka consumers — only register when explicitly enabled
if ORCHESTRATION_KAFKA_ENABLED:
    CELERY_BEAT_SCHEDULE.update(
        {
            "consume-pipeline-results-every-10s": {
                "task": "orchestration.tasks.consume_pipeline_results",
                "schedule": 10.0,
            },
            "consume-agent-traces-every-5s": {
                "task": "orchestration.tasks.consume_agent_traces",
                "schedule": 5.0,
            },
            "emit-tcia-daily-scan": {
                "task": "orchestration.tasks.emit_tcia_daily_scan",
                "schedule": 3600.0,  # Every hour (task checks optimal_hour)
            },
            "emit-tcia-weekly-report": {
                "task": "orchestration.tasks.emit_tcia_weekly_report",
                "schedule": 3600.0,  # Hourly; task guards for Monday 04:00 UTC
            },
        }
    )

# DB-to-RAG periodic sync — only register when enabled
if RAG_DB_SYNC_ENABLED:
    CELERY_BEAT_SCHEDULE["periodic-db-rag-sync"] = {
        "task": "rag_index.tasks.periodic_db_rag_sync",
        "schedule": float(RAG_DB_SYNC_PERIODIC_INTERVAL),
    }

# Analytics rollup reconciliation — nightly at 02:00 UTC
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE["reconcile-analytics-rollups"] = {
    "task": "analytics.tasks.reconcile_rollups_task",
    "schedule": crontab(hour=2, minute=0),
}

# ILA: expire stale WF2 approval requests hourly
CELERY_BEAT_SCHEDULE["expire-ila-wf2-requests"] = {
    "task": "intelligence_loop.tasks.expire_pending_wf2_requests",
    "schedule": 3600.0,
}

# --- Pipeline Orchestration Settings ---
# URL of the external pipeline-orchestrator-svc (LangGraph)
ORCHESTRATOR_URL = config("ORCHESTRATOR_URL", default="http://localhost:8010")
# Service-to-service auth token for dispatch calls (core-api → orchestrator)
ORCHESTRATOR_SERVICE_TOKEN = config(
    "ORCHESTRATOR_SERVICE_TOKEN", default="dev-service-token"
)
# Shared secret for authenticating pipeline callbacks (orchestrator → core-api)
ORCHESTRATOR_CALLBACK_TOKEN = config(
    "ORCHESTRATOR_CALLBACK_TOKEN", default="dev-callback-token"
)
# Continuous Optimization Agent (COA) — used to proxy manual tick triggers
COA_SERVICE_URL = config("COA_SERVICE_URL", default="http://localhost:8044")
COA_SERVICE_TOKEN = config("COA_SERVICE_TOKEN", default="dev-service-token")
# Intelligence Loop Agent (ILA, WF3.5) — used to proxy manual triggers and
# to authenticate ILA → Django ingest endpoints via X-Service-Token.
ILA_SERVICE_URL = config(
    "ILA_SERVICE_URL", default="http://intelligence-loop-agent-svc:8045"
)
ILA_SERVICE_TOKEN = config("ILA_SERVICE_TOKEN", default="dev-service-token")
# HTTP timeout (seconds) when dispatching jobs to the orchestrator
ORCHESTRATOR_TIMEOUT = config("ORCHESTRATOR_TIMEOUT", default=30, cast=int)
# Backend URL for orchestrator callbacks (used to build callback_url in dispatch)
BACKEND_URL = config("BACKEND_URL", default="http://localhost:8001")

# --------------------------------------------------------------------------
# Chat Titling Worker
# --------------------------------------------------------------------------
# Shared secret for authenticating title updates (titling-worker → core-api).
# Defaults to a dev-only value; in production (DEBUG=False) it must be set
# explicitly via the WORKER_TOKEN env var or the endpoint will reject all
# requests (fail closed).
BRAND_POSITIONING_AGENT_URL = config(
    "BRAND_POSITIONING_AGENT_URL",
    default="http://brand-positioning-agent-svc:8031",
)
BRAND_ARCHITECTURE_AGENT_URL = config(
    "BRAND_ARCHITECTURE_AGENT_URL",
    default="http://brand-architecture-agent-svc:8032",
)

WORKER_TOKEN = config("WORKER_TOKEN", default="dev-worker-token" if DEBUG else "")
# Enable Kafka-based titling (set true when chat-titling-worker is deployed)
TITLING_KAFKA_ENABLED = config("TITLING_KAFKA_ENABLED", default=False, cast=bool)
