# Generated by Django 4.2.16 on 2026-01-23 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0009_add_instagram_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleBusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_access_token",
                    models.TextField(blank=True, db_column="access_token", null=True),
                ),
                (
                    "_refresh_token",
                    models.TextField(blank=True, db_column="refresh_token", null=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "google_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "gbp_account_id",
                    models.CharField(
                        blank=True,
                        help_text="accounts/{account_id} resource name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gbp_account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("expired", "Token Expired"),
                            ("error", "Error"),
                            ("pending_verification", "Pending Verification"),
                        ],
                        default="disconnected",
                        max_length=25,
                    ),
                ),
                (
                    "is_mock",
                    models.BooleanField(
                        default=False, help_text="True if connected via mock/test mode"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_business_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Business Profile",
                "verbose_name_plural": "Google Business Profiles",
            },
        ),
        migrations.CreateModel(
            name="GoogleBusinessLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_id",
                    models.CharField(
                        help_text="locations/{location_id} resource name",
                        max_length=255,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("primary_category", models.CharField(blank=True, max_length=255)),
                (
                    "primary_category_id",
                    models.CharField(
                        blank=True,
                        help_text="categories/gcid:xxx format",
                        max_length=255,
                    ),
                ),
                ("additional_categories", models.JSONField(blank=True, default=list)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("website_url", models.URLField(blank=True)),
                (
                    "business_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Regular business hours by day",
                    ),
                ),
                (
                    "special_hours",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Special hours for holidays, etc.",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Verification Pending"),
                            ("verified", "Verified"),
                            ("failed", "Verification Failed"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("is_synced", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="automation.googlebusinessprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Business Location",
                "verbose_name_plural": "Google Business Locations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="googlebusinessprofile",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_gbp_connection"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="googlebusinesslocation",
            unique_together={("profile", "location_id")},
        ),
    ]
