# Generated by Django 4.2.16 on 2026-02-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_domain_options_tenant_schema_name_and_more"),
        ("automation", "0010_google_business_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtask",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_tasks",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="contentcalendar",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_content",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="facebookresumableupload",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facebook_uploads",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="googlebusinessprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_business_profiles",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="instagramresumableupload",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instagram_uploads",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="oauthstate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_states",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_profiles",
                to="tenants.tenant",
            ),
        ),
    ]
