# Generated by Django 4.2.16 on 2026-08-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="google_calendar", max_length=32),
                ),
                (
                    "_refresh_token",
                    models.TextField(blank=True, db_column="refresh_token", default=""),
                ),
                (
                    "scope",
                    models.CharField(
                        default="https://www.googleapis.com/auth/calendar.events",
                        help_text="The narrowest scope that supports read plus event creation, per the card: calendar.events, not calendar. A full-calendar grant would let this app delete an operator's personal appointments.",
                        max_length=255,
                    ),
                ),
                (
                    "google_account_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("NEEDS_RECONNECT", "Needs reconnect"),
                            ("DISCONNECTED", "Disconnected"),
                        ],
                        db_index=True,
                        default="CONNECTED",
                        max_length=24,
                    ),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Non-null: a connection belongs to somebody, always",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="calendarconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DISCONNECTED"), _negated=True),
                fields=("tenant", "provider"),
                name="one_live_calendar_connection_per_tenant",
            ),
        ),
    ]
