# Generated by Django 4.2.16 on 2026-08-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarconnection",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="last_sync_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="sync_backoff_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="sync_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="sync_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
