# Generated by Django 4.2.16 on 2026-04-07 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("optimization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0008_add_vertex_ai_data_store_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intelligence_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "job_id",
                    models.CharField(
                        db_index=True,
                        help_text="ILA run id (orchestrator job_id or internal uuid).",
                        max_length=64,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("store_only", "Store Only"),
                            ("auto_trigger", "Auto Trigger"),
                        ],
                        default="store_only",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("kafka_completed", "Kafka campaign.completed"),
                            ("coa_event", "COA action_executed"),
                            ("weekly_tick", "Celery Beat weekly tick"),
                            ("manual", "Manual / on-demand"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "intelligence_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Synthesized narrative + summary from ILA scorer.",
                    ),
                ),
                ("auto_reruns_triggered", models.PositiveIntegerField(default=0)),
                ("contradictions", models.JSONField(blank=True, default=list)),
                ("rag_writes", models.PositiveIntegerField(default=0)),
                (
                    "brand_context_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_reports",
                        to="optimization.campaignregistry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_reports",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learning_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("audience", "Audience"),
                            ("messaging", "Messaging"),
                            ("creative", "Creative"),
                            ("funnel", "Funnel"),
                            ("competitive", "Competitive"),
                        ],
                        max_length=16,
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured payload + evidence + sample_size.",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        help_text="Final scored confidence (0-100)."
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "target_workflow",
                    models.CharField(
                        choices=[
                            ("WF1", "Workflow 1 — Research"),
                            ("WF2", "Workflow 2 — Strategy"),
                            ("WF3", "Workflow 3 — Campaigns"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "target_agent",
                    models.CharField(
                        help_text="Target agent code (APA, BPA, BPV, NTA, BSA, CAA, CIA…).",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                            ("saved", "Saved"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "rag_document_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learnings",
                        to="intelligence_loop.campaignintelligence",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Retrieval text written into RAG."),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured metadata used as Vertex AI document filters: category, impact, confidence, campaign_id, brand_context_id.",
                    ),
                ),
                (
                    "vector_doc_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vertex AI document ID, populated by sync task.",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_document",
                        to="intelligence_loop.learningrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_documents",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WF2RerunRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "requested_agent",
                    models.CharField(
                        help_text="WF2 agent code (BPA|BAA|BPV|NTA|BSA).", max_length=16
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_by", models.CharField(default="ila", max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Auto-expire after ILA_WF2_APPROVAL_TIMEOUT_HOURS (default 72h)."
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AnalysisJob id once dispatched on approval.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wf2_rerun_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wf2_rerun_requests",
                        to="intelligence_loop.learningrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wf2_rerun_requests",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="idx_ila_wf2req_tenant_status"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="learningrecord",
            index=models.Index(
                fields=["tenant", "category", "status"], name="idx_ila_learn_tenant_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="learningrecord",
            index=models.Index(
                fields=["intelligence", "category"], name="idx_ila_learn_intel_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignintelligence",
            index=models.Index(
                fields=["tenant", "-created_at"], name="idx_ila_intel_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignintelligence",
            index=models.Index(
                fields=["campaign", "-created_at"], name="idx_ila_intel_camp_created"
            ),
        ),
    ]
