"""Generate a branded PDF report from brand equity results."""

import logging
from typing import Any

from fpdf import FPDF

logger = logging.getLogger(__name__)


def generate_brand_equity_pdf(result: dict[str, Any]) -> bytes:
    """Generate a professional PDF report from brand equity results.

    Returns the PDF as bytes suitable for email attachment or download.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 12, "Brand Equity Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        6,
        f"ISO 20671:2019 | {result.get('methodology', '')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(6)

    # ── Company + Overall Score ──
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, result.get("company_name", ""), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 28)
    score = result.get("overall_score", 0)
    pdf.cell(0, 14, f"Overall Score: {score}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # ── Dimension Breakdown ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Dimension Breakdown", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    for dim in result.get("dimensions", []):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(
            0,
            7,
            f"{dim.get('name', '')} — {dim.get('score', 0)}/100 (Weight: {int(dim.get('weight', 0) * 100)}%)",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.set_font("Helvetica", "", 10)
        rationale = dim.get("rationale", "")
        if rationale:
            pdf.multi_cell(0, 5, rationale)
        factors = dim.get("key_factors", [])
        if factors:
            pdf.set_font("Helvetica", "I", 9)
            pdf.multi_cell(0, 5, "Key factors: " + ", ".join(factors))
        pdf.ln(3)

    # ── Competitor Analysis ──
    competitors = result.get("competitors", [])
    if competitors:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Competitor Analysis", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for comp in competitors:
            pdf.set_font("Helvetica", "B", 11)
            hq = comp.get("headquarters", "")
            label = comp.get("name", "")
            if hq:
                label += f" ({hq})"
            pdf.cell(
                0,
                7,
                f"{label} — Score: {comp.get('estimated_score', 0)}/100",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.set_font("Helvetica", "", 10)
            for s in comp.get("strengths", []):
                pdf.cell(0, 5, f"  + {s}", new_x="LMARGIN", new_y="NEXT")
            for w in comp.get("weaknesses", []):
                pdf.cell(0, 5, f"  - {w}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

    # ── Formula ──
    formula = result.get("formula_explanation", "")
    if formula:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "How We Calculated This", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Courier", "", 9)
        pdf.multi_cell(0, 5, formula)
        pdf.ln(4)

    # ── Derivation ──
    derivation = result.get("derivation", "")
    if derivation:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Step-by-Step Derivation", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, derivation)
        pdf.ln(4)

    # ── Limitations ──
    limitations = result.get("limitations", [])
    if limitations:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Limitations", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        for lim in limitations:
            pdf.multi_cell(0, 5, f"• {lim}")
            pdf.ln(1)
        pdf.ln(3)

    # ── Recommendations ──
    recs = result.get("recommendations", [])
    if recs:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Recommendations", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        for i, rec in enumerate(recs, 1):
            pdf.multi_cell(0, 5, f"{i}. {rec}")
            pdf.ln(1)

    # ── Footer ──
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(
        0,
        5,
        "Generated by AI Brand Automator | Powered by Claude AI",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 5, "https://aibrandautomator.com", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
