from django.core.management.base import BaseCommand

from analytics.models import MetricDefinition

METRIC_DEFINITIONS = [
    {
        "metric_name": "nps",
        "display_name": "Net Promoter Score",
        "category": "customer_voice",
        "unit": "score",
        "value_range_min": -100,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#00F5FF",
        "display_order": 1,
        "description": "Net Promoter Score from Voice of Customer analysis",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
            "brand-analysis",
        ],
    },
    {
        "metric_name": "voc_health_score",
        "display_name": "VoC Health Score",
        "category": "customer_voice",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#10B981",
        "display_order": 2,
        "description": "Overall Voice of Customer health score",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
            "brand-analysis",
        ],
    },
    {
        "metric_name": "sentiment_positive_pct",
        "display_name": "Positive Sentiment",
        "category": "customer_voice",
        "unit": "percent",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#34D399",
        "display_order": 3,
        "description": "Percentage of positive sentiment in customer feedback",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "sentiment_negative_pct",
        "display_name": "Negative Sentiment",
        "category": "customer_voice",
        "unit": "percent",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": False,
        "chart_color": "#EF4444",
        "display_order": 4,
        "description": "Percentage of negative sentiment in customer feedback",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "pain_points_count",
        "display_name": "Pain Points Identified",
        "category": "customer_voice",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 1000,
        "higher_is_better": False,
        "chart_color": "#F59E0B",
        "display_order": 5,
        "description": "Number of customer pain points identified",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "data_coverage_pct",
        "display_name": "Data Coverage",
        "category": "customer_voice",
        "unit": "percent",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#8B5CF6",
        "display_order": 6,
        "description": "Percentage of data sources covered in VoC analysis",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "trends_identified",
        "display_name": "Trends Identified",
        "category": "trend_analysis",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 1000,
        "higher_is_better": True,
        "chart_color": "#06B6D4",
        "display_order": 7,
        "description": "Number of cultural and market trends identified",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "personas_count",
        "display_name": "Personas Profiled",
        "category": "audience",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#EC4899",
        "display_order": 8,
        "description": "Number of audience personas profiled",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
        ],
    },
    {
        "metric_name": "competitors_tracked",
        "display_name": "Competitors Tracked",
        "category": "competitive",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#F97316",
        "display_order": 9,
        "description": "Number of competitors analyzed",
        "source_pipelines": [
            "brand-discovery-complete",
            "brand-discovery-full",
            "brand-analysis",
            "competitor-audit",
        ],
    },
    {
        "metric_name": "brand_equity_awareness",
        "display_name": "Brand Awareness",
        "category": "brand_equity",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#3B82F6",
        "display_order": 10,
        "description": "ISO 10668 brand awareness score",
        "source_pipelines": ["iso-brand-equity"],
    },
    {
        "metric_name": "brand_equity_sentiment",
        "display_name": "Brand Sentiment",
        "category": "brand_equity",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#6366F1",
        "display_order": 11,
        "description": "ISO 10668 brand sentiment score",
        "source_pipelines": ["iso-brand-equity"],
    },
    {
        "metric_name": "brand_equity_financials",
        "display_name": "Brand Financials",
        "category": "brand_equity",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#14B8A6",
        "display_order": 12,
        "description": "ISO 10668 brand financial strength score",
        "source_pipelines": ["iso-brand-equity"],
    },
    {
        "metric_name": "brand_value_npv",
        "display_name": "Brand Value (NPV)",
        "category": "brand_equity",
        "unit": "currency",
        "value_range_min": 0,
        "value_range_max": 999999999999,
        "higher_is_better": True,
        "chart_color": "#22C55E",
        "display_order": 13,
        "description": "Net present value of brand equity",
        "source_pipelines": ["iso-brand-equity"],
    },
    # ── Brand Positioning (WF2 Agent 2.1) ──
    {
        "metric_name": "positioning_clarity_score",
        "display_name": "Positioning Clarity",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#3B82F6",
        "display_order": 100,
        "description": "Clarity score of recommended positioning statement",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "positioning_differentiation_score",
        "display_name": "Positioning Differentiation",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#8B5CF6",
        "display_order": 101,
        "description": "Differentiation score of recommended positioning",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "positioning_believability_score",
        "display_name": "Positioning Believability",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#14B8A6",
        "display_order": 102,
        "description": "Believability score of recommended positioning",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "positioning_memorability_score",
        "display_name": "Positioning Memorability",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#F59E0B",
        "display_order": 103,
        "description": "Memorability score of recommended positioning",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "positioning_overall_score",
        "display_name": "Positioning Overall Score",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#00F5FF",
        "display_order": 104,
        "description": "Overall quality score of recommended positioning",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "differentiation_score",
        "display_name": "Differentiation Score",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#EC4899",
        "display_order": 105,
        "description": "Overall differentiation framework score",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "value_prop_fit_score",
        "display_name": "Value Prop Canvas Fit",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#10B981",
        "display_order": 106,
        "description": "Value Proposition Canvas fit score",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "points_of_difference_count",
        "display_name": "Points of Difference",
        "category": "brand_positioning",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 20,
        "higher_is_better": True,
        "chart_color": "#8B5CF6",
        "display_order": 107,
        "description": "Number of Points of Difference (PODs) identified",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "points_of_parity_count",
        "display_name": "Points of Parity",
        "category": "brand_positioning",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 20,
        "higher_is_better": True,
        "chart_color": "#6B7280",
        "display_order": 108,
        "description": "Number of Points of Parity (POPs) identified",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "perceptual_maps_generated",
        "display_name": "Perceptual Maps Generated",
        "category": "brand_positioning",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 5,
        "higher_is_better": True,
        "chart_color": "#3B82F6",
        "display_order": 109,
        "description": "Number of perceptual maps generated",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "primary_map_differentiation_potential",
        "display_name": "Primary Map Differentiation",
        "category": "brand_positioning",
        "unit": "score",
        "value_range_min": 0,
        "value_range_max": 100,
        "higher_is_better": True,
        "chart_color": "#00F5FF",
        "display_order": 110,
        "description": "Differentiation potential of primary perceptual map",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "competitive_white_space_zones",
        "display_name": "Competitive White Spaces",
        "category": "brand_positioning",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 20,
        "higher_is_better": True,
        "chart_color": "#22C55E",
        "display_order": 111,
        "description": "Number of competitive white-space zones identified",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    {
        "metric_name": "positioning_candidates_generated",
        "display_name": "Positioning Candidates",
        "category": "brand_positioning",
        "unit": "count",
        "value_range_min": 0,
        "value_range_max": 7,
        "higher_is_better": True,
        "chart_color": "#F59E0B",
        "display_order": 112,
        "description": "Number of positioning candidates generated",
        "source_pipelines": ["brand-strategy-positioning"],
    },
    # ── Brand Architecture (BAA) metrics ──
    {
        "metric_name": "architecture_model_score",
        "display_name": "Architecture Model Score",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 100,
        "higher_is_better": True,
        "chart_color": "#3B82F6",
        "display_order": 200,
        "description": "Total score for recommended architecture model (4 dimensions x 0-25)",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "architecture_positioning_alignment",
        "display_name": "Positioning Alignment",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 25,
        "higher_is_better": True,
        "chart_color": "#8B5CF6",
        "display_order": 201,
        "description": "Architecture alignment with BPA positioning strategy",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "architecture_audience_fit",
        "display_name": "Audience Fit",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 25,
        "higher_is_better": True,
        "chart_color": "#14B8A6",
        "display_order": 202,
        "description": "Architecture fit with target audience segments",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "architecture_competitive_diff",
        "display_name": "Competitive Differentiation",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 25,
        "higher_is_better": True,
        "chart_color": "#F59E0B",
        "display_order": 203,
        "description": "Architecture competitive differentiation score",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "architecture_operational_efficiency",
        "display_name": "Operational Efficiency",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 25,
        "higher_is_better": True,
        "chart_color": "#EC4899",
        "display_order": 204,
        "description": "Operational efficiency of recommended architecture",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "hierarchy_depth",
        "display_name": "Hierarchy Depth",
        "category": "brand_architecture",
        "unit": "count",
        "min_value": 0,
        "max_value": 5,
        "higher_is_better": False,
        "chart_color": "#6B7280",
        "display_order": 205,
        "description": "Depth of brand hierarchy tree (deeper = more complex)",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "sub_brand_count",
        "display_name": "Sub-Brand Count",
        "category": "brand_architecture",
        "unit": "count",
        "min_value": 0,
        "max_value": 15,
        "higher_is_better": True,
        "chart_color": "#22C55E",
        "display_order": 206,
        "description": "Number of sub-brands in hierarchy tree",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "naming_consistency_score",
        "display_name": "Naming Consistency",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 100,
        "higher_is_better": True,
        "chart_color": "#00F5FF",
        "display_order": 207,
        "description": "Consistency score for naming conventions across hierarchy",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "growth_phases_planned",
        "display_name": "Growth Phases Planned",
        "category": "brand_architecture",
        "unit": "count",
        "min_value": 0,
        "max_value": 10,
        "higher_is_better": True,
        "chart_color": "#F59E0B",
        "display_order": 208,
        "description": "Number of portfolio growth phases planned",
        "source_pipelines": ["brand-strategy-architecture"],
    },
    {
        "metric_name": "architecture_confidence",
        "display_name": "Architecture Confidence",
        "category": "brand_architecture",
        "unit": "score",
        "min_value": 0,
        "max_value": 100,
        "higher_is_better": True,
        "chart_color": "#10B981",
        "display_order": 209,
        "description": "Overall confidence in architecture recommendation",
        "source_pipelines": ["brand-strategy-architecture"],
    },
]


class Command(BaseCommand):
    help = "Seed MetricDefinition rows for workflow analytics"

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for defn in METRIC_DEFINITIONS:
            _, was_created = MetricDefinition.objects.update_or_create(
                metric_name=defn["metric_name"],
                defaults=defn,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} new, updated {updated} existing "
                f"MetricDefinition rows (total: {len(METRIC_DEFINITIONS)})"
            )
        )
