# Generated by Django 4.2.16 on 2026-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_domain_options_tenant_schema_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="gcs_curated_bucket",
            field=models.CharField(
                blank=True,
                help_text="GCS bucket for curated assets. Leave blank for shared default.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="gcs_raw_bucket",
            field=models.CharField(
                blank=True,
                help_text="GCS bucket for raw/ingestion assets. Leave blank for shared default.",
                max_length=255,
            ),
        ),
    ]
