# Generated by Django 4.2.16 on 2026-02-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Generate unique slugs for all existing tenants."""
    Tenant = apps.get_model("tenants", "Tenant")
    used_slugs = set()

    for tenant in Tenant.objects.all().order_by("id"):
        base_slug = slugify(tenant.name) if tenant.name else ""
        if not base_slug:
            # Fallback: derive from schema_name
            base_slug = tenant.schema_name.replace("user_", "user-")
        if not base_slug:
            base_slug = f"workspace-{tenant.id}"

        slug = base_slug
        counter = 1
        while slug in used_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1

        tenant.slug = slug
        tenant.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0004_add_gcs_bucket_fields"),
    ]

    operations = [
        # Step 1: Add slug without unique constraint
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="URL-friendly identifier, auto-generated from name",
                max_length=100,
            ),
        ),
        # Step 2: Backfill slugs for existing tenants
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Step 3: Add the unique constraint via raw SQL to avoid
        # Django re-creating the _like index (AlterField would do that)
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant ADD CONSTRAINT tenants_tenant_slug_key UNIQUE (slug);",
            reverse_sql="ALTER TABLE tenants_tenant DROP CONSTRAINT IF EXISTS tenants_tenant_slug_key;",
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="editor",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable without removing the record",
                    ),
                ),
                ("invited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-invited_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant"), name="unique_membership_per_user_tenant"
            ),
        ),
    ]
