# Generated by Django 4.2.16 on 2026-02-10 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0005_add_membership_and_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership_per_user_tenant",
        ),
        migrations.AddField(
            model_name="membership",
            name="invited_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for pending invites (user not yet registered).",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for pending invitations to users not yet registered.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "tenant"),
                name="unique_membership_per_user_tenant",
            ),
        ),
    ]
