# Generated by Django 4.2.16 on 2026-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_membership_nullable_user_invited_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="invite_token",
            field=models.UUIDField(
                blank=True,
                help_text="Unique token for accepting an invitation via link.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier, auto-generated from name",
                max_length=100,
                unique=True,
            ),
        ),
    ]
