# Generated by Django 4.2.16 on 2026-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_add_invite_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="vertex_ai_data_store_id",
            field=models.CharField(
                blank=True,
                help_text="Vertex AI data store ID. Leave blank for shared default.",
                max_length=255,
            ),
        ),
    ]
