# Generated by Django 4.2.16 on 2026-03-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("orchestration", "0004_trendnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
                ("value_range_min", models.FloatField(default=0)),
                ("value_range_max", models.FloatField(default=100)),
                ("higher_is_better", models.BooleanField(default=True)),
                ("chart_color", models.CharField(default="#00F5FF", max_length=7)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("source_pipelines", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "metric_name"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_id", models.SlugField(max_length=100)),
                ("metric_name", models.CharField(db_index=True, max_length=100)),
                ("metric_value", models.FloatField()),
                ("metric_unit", models.CharField(default="score", max_length=20)),
                ("metric_category", models.CharField(db_index=True, max_length=50)),
                (
                    "agent_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="orchestration.analysisjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "pipeline_id", "metric_name", "recorded_at"],
                        name="idx_snap_tnt_pipe_metric",
                    ),
                    models.Index(
                        fields=["tenant", "metric_category", "recorded_at"],
                        name="idx_snap_tnt_category",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_id", models.SlugField(max_length=100)),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_category", models.CharField(max_length=50)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("avg_value", models.FloatField()),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                ("latest_value", models.FloatField()),
                ("sample_count", models.PositiveIntegerField()),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("change_pct", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_rollups",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "period", "period_start"],
                        name="idx_rollup_tenant_period",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="metricrollup",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "pipeline_id",
                    "metric_name",
                    "period",
                    "period_start",
                ),
                name="unique_rollup_tenant_pipe_metric_period",
            ),
        ),
    ]
