# Generated by Django 4.2.16 on 2026-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="metricsnapshot",
            constraint=models.UniqueConstraint(
                fields=("tenant", "job", "metric_name"),
                name="unique_snap_tenant_job_metric",
            ),
        ),
    ]
