# Generated by Django 4.2.16 on 2026-04-06 01:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("onboarding", "0009_add_website_field"),
        ("tenants", "0008_add_vertex_ai_data_store_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Internal campaign identifier",
                        unique=True,
                    ),
                ),
                (
                    "meta_campaign_id",
                    models.CharField(help_text="Meta Ads campaign ID", max_length=100),
                ),
                (
                    "meta_ad_account_id",
                    models.CharField(
                        help_text="Meta Ads ad account ID", max_length=100
                    ),
                ),
                ("campaign_name", models.CharField(max_length=500)),
                (
                    "objective",
                    models.CharField(
                        help_text="Campaign objective (CONVERSIONS, REACH, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "optimization_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("autonomous", "Autonomous")],
                        default="manual",
                        help_text="Manual: recommendations need approval. Autonomous: auto-execute within guardrails.",
                        max_length=20,
                    ),
                ),
                (
                    "target_cpa_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target cost per acquisition in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "target_roas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target return on ad spend",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "daily_budget_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Daily budget in USD", max_digits=10
                    ),
                ),
                (
                    "lifetime_budget_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lifetime budget in USD",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "ad_sets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, name, status, targeting, daily_budget}]",
                    ),
                ),
                (
                    "ads",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, ad_set_id, name, status, creative_id}]",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "guardrail_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-campaign guardrail overrides",
                    ),
                ),
                (
                    "source_job_id",
                    models.UUIDField(
                        blank=True,
                        help_text="AnalysisJob that published this campaign",
                        null=True,
                    ),
                ),
                (
                    "brand_context_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sandbox_mode", models.BooleanField(default=True)),
                (
                    "meta_access_token_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to encrypted Meta access token in tenant config",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_registries",
                        to="onboarding.company",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_registries",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_id",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("PAUSE", "Pause"),
                            ("SCALE", "Scale Budget"),
                            ("REALLOCATE", "Reallocate Budget"),
                            ("REFRESH", "Creative Refresh"),
                            ("ADJUST_BID", "Adjust Bid"),
                            ("ADJUST_PLACEMENT", "Adjust Placement"),
                            ("ADJUST_SCHEDULE", "Adjust Schedule"),
                            ("ACTIVATE", "Activate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign"),
                            ("ad_set", "Ad Set"),
                            ("ad", "Ad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="Meta entity ID", max_length=100),
                ),
                ("current_values", models.JSONField(blank=True, default=dict)),
                ("proposed_values", models.JSONField(blank=True, default=dict)),
                (
                    "rationale",
                    models.TextField(help_text="Analysis rationale with data points"),
                ),
                (
                    "projected_impact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estimated savings or ROI improvement",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                            ("expired", "Expired"),
                            ("executed", "Executed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "modified_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-modified values before approval",
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Auto-expire after 48h")),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tick_id",
                    models.CharField(
                        help_text="Optimization tick that generated this",
                        max_length=255,
                    ),
                ),
                (
                    "data_freshness",
                    models.DateTimeField(
                        help_text="When Meta Insights data was fetched"
                    ),
                ),
                (
                    "guardrails_applied",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Guardrail IDs that were evaluated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="optimization.campaignregistry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_recommendations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("action_type", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("autonomous", "Autonomous")],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                ("guardrails_applied", models.JSONField(blank=True, default=list)),
                ("meta_api_response", models.JSONField(blank=True, default=dict)),
                ("verified", models.BooleanField(default=False)),
                ("verification_result", models.JSONField(blank=True, default=dict)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="optimization.campaignregistry",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for autonomous actions without prior recommendation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="optimization.optimizationrecommendation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_actions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="optimizationrecommendation",
            index=models.Index(
                fields=["tenant", "status"], name="idx_opt_rec_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrecommendation",
            index=models.Index(
                fields=["campaign", "status"], name="idx_opt_rec_campaign_status"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationaction",
            index=models.Index(
                fields=["tenant", "campaign"], name="idx_opt_action_tenant_campaign"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignregistry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "meta_campaign_id"),
                name="unique_tenant_meta_campaign",
            ),
        ),
    ]
