# Generated by Django 4.2.16 on 2026-04-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignregistry",
            name="actual_cpa_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest observed cost per acquisition in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignregistry",
            name="actual_ctr",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Latest observed click-through rate (0.0-1.0)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignregistry",
            name="actual_roas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest observed return on ad spend",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignregistry",
            name="actual_spend_today_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Spend today in USD (from latest tick)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignregistry",
            name="last_metrics_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the latest performance metrics update",
                null=True,
            ),
        ),
    ]
