# Generated by Django 4.2.16 on 2026-02-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0005_alter_company_values_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandasset",
            name="pipeline_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error message if pipeline processing failed",
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="pipeline_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ingested", "Ingested"),
                    ("curated", "Curated"),
                    ("indexed", "Indexed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Current status in the data pipeline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="pipeline_trace_id",
            field=models.UUIDField(
                blank=True,
                help_text="Trace ID for tracking through the pipeline",
                null=True,
            ),
        ),
    ]
