# Generated by hand to backfill pipeline_status for existing assets

from django.db import migrations


def backfill_pipeline_status(apps, schema_editor):
    """
    Backfill pipeline_status for existing assets.

    Assets that have processed=True should have pipeline_status='indexed'
    since they were processed before the pipeline was added.
    """
    BrandAsset = apps.get_model("onboarding", "BrandAsset")

    # Update processed assets to indexed status
    updated = BrandAsset.objects.filter(
        processed=True,
        pipeline_status="pending",
    ).update(pipeline_status="indexed")

    if updated:
        print(f"  Backfilled {updated} processed assets to pipeline_status='indexed'")


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill - set all indexed assets back to pending.
    This is safe because we're only reverting our data change.
    """
    BrandAsset = apps.get_model("onboarding", "BrandAsset")

    BrandAsset.objects.filter(
        processed=True,
        pipeline_status="indexed",
    ).update(pipeline_status="pending")


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0006_add_pipeline_status"),
    ]

    operations = [
        migrations.RunPython(backfill_pipeline_status, reverse_backfill),
    ]
