# Generated by Django 4.2.16 on 2026-02-08 01:14

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def deduplicate_brand_assets(apps, schema_editor):
    """
    Remove duplicate BrandAsset rows before adding the unique constraint.
    Keeps the row with the highest id for each (tenant, company, file_name)
    combination and deletes the older duplicates using a single SQL statement
    with a window function for predictable runtime on large tables.
    """
    BrandAsset = apps.get_model("onboarding", "BrandAsset")
    db_table = BrandAsset._meta.db_table

    # Single set-based DELETE using ROW_NUMBER() window function.
    # Partitions by the unique key columns and keeps only the row with
    # the highest id (rn=1) in each group, deleting all others.
    sql = f"""
        DELETE FROM {db_table} ba
        USING (
            SELECT id
            FROM (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY tenant_id, company_id, file_name
                        ORDER BY id DESC
                    ) AS rn
                FROM {db_table}
            ) sub
            WHERE rn > 1
        ) dups
        WHERE ba.id = dups.id;
    """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)
        total_deleted = cursor.rowcount

    if total_deleted:
        logger.info("Removed %d duplicate BrandAsset row(s).", total_deleted)


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0007_backfill_pipeline_status"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_brand_assets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="brandasset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "file_name"),
                name="unique_brand_asset_per_tenant_company",
            ),
        ),
    ]
