# Generated by Django 4.2.16 on 2026-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0007_backfill_pipeline_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="brandasset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "file_name"),
                name="unique_brand_asset_per_tenant_company",
            ),
        ),
    ]
