# Generated by Django 4.2.16 on 2026-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_add_unique_brand_asset_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Company website URL (optional)",
                max_length=500,
            ),
        ),
    ]
