# Generated by Django 4.2.16 on 2026-07-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_add_brandasset_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandasset',
            name='gcs_bucket',
            field=models.CharField(default='zorven-raw-assets', max_length=100),
        ),
    ]
