# Generated by Django 4.2.16 on 2026-08-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0001_initial"),
        ("onboarding", "0012_alter_brandasset_gcs_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandasset",
            name="ocr_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence of the OCR pass that produced ocr_text (H-03)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="ocr_text",
            field=models.TextField(
                blank=True,
                help_text="REDACTED OCR text only. The unredacted output must never reach this column — Design §5.2 PG-08 requires redaction before persistence, and H-03 implements it. Do not 'helpfully' store the raw text here. Written by H-03, not by the upload flow. H-03 also owns carrying this into RAG metadata, which B-02 deliberately does not do (see test_rag_metadata.py).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="onboarding_session",
            field=models.ForeignKey(
                blank=True,
                help_text="The session this was captured during, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captured_media",
                to="onboarding_sessions.onboardingsession",
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="usage_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("business_photo", "Business photo"),
                    ("previous_ad", "Previous ad"),
                    ("identity_document", "Identity document"),
                    ("brand_asset", "Brand asset"),
                    ("other", "Other"),
                ],
                help_text="What this asset is, as declared at capture. Carried into RAG document metadata so WF3 can retrieve prior ads by intent.",
                max_length=32,
                null=True,
            ),
        ),
    ]
