# Generated by Django 4.2.16 on 2026-08-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0013_brandasset_ocr_confidence_brandasset_ocr_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="audience_languages",
            field=models.JSONField(
                blank=True,
                help_text='["en-IN", "kn-IN"] — BCP-47, matching §10.2.1 config.language',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="brand_asset_status",
            field=models.CharField(
                blank=True,
                help_text="What brand assets exist today (logo, guidelines, none)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="business_goals",
            field=models.TextField(
                blank=True, help_text="What the business wants to achieve", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="competitors",
            field=models.JSONField(
                blank=True,
                help_text='[{"name": str, "url": str?, "notes": str?}]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="customer_proof",
            field=models.JSONField(
                blank=True,
                help_text='[{"type": "testimonial|review|case_study|award", "text": str, "source": str?, "date": str?}]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="decision_maker",
            field=models.CharField(
                blank=True,
                help_text="Who signs off on brand and campaign decisions",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="digital_presence",
            field=models.JSONField(
                blank=True,
                help_text='{"website": str?, "instagram": str?, ... } — handles/URLs',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="founder_story",
            field=models.TextField(
                blank=True, help_text="Origin story, in the founder's words", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Registered legal entity name, where it differs from name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="marketing_budget_range",
            field=models.JSONField(
                blank=True,
                help_text='{"currency": "INR", "min": 50000, "max": 200000?, "period": "monthly"} — a numeric range with an ISO 4217 code rather than a band enum, because a band cannot be multi-currency without an FX rate baked into the schema. Cross-currency comparison is the caller\'s job.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="products_services",
            field=models.JSONField(
                blank=True,
                help_text='[{"name": str, "description": str?, "price_range": str?}]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sales_channels",
            field=models.JSONField(
                blank=True,
                help_text='[{"channel": "online_store|marketplace|retail|wholesale|direct|social", "notes": str?}]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="trademark_status",
            field=models.CharField(
                blank=True,
                help_text="Trademark position — registered, pending, none",
                max_length=255,
                null=True,
            ),
        ),
    ]
