# Generated by Django 4.2.16 on 2026-08-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0014_company_audience_languages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandasset",
            name="rag_excluded",
            field=models.BooleanField(
                default=False,
                help_text="True when PG-08 excludes this asset from RAG due to sensitivity that cannot be redacted.",
            ),
        ),
        migrations.AddField(
            model_name="brandasset",
            name="sensitivity_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENERAL", "General"),
                    ("IDENTITY", "Identity"),
                    ("FINANCIAL", "Financial"),
                ],
                help_text="Sensitivity classification from OCR analysis (H-03)",
                max_length=20,
                null=True,
            ),
        ),
    ]
