# Generated by Django 4.2.16 on 2026-08-01 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onboarding", "0012_alter_brandasset_gcs_bucket"),
        ("tenants", "0008_add_vertex_ai_data_store_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("MEETING_LIVE", "Meeting live"),
                            ("GATHERED", "Gathered"),
                            ("PROCESSING", "Processing"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("ESCALATED", "Escalated"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "escalated_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("MEETING_LIVE", "Meeting live"),
                            ("GATHERED", "Gathered"),
                            ("PROCESSING", "Processing"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("ESCALATED", "Escalated"),
                            ("ARCHIVED", "Archived"),
                        ],
                        help_text="Status held before escalation, restored on resolution. Without it the agent would have to guess, and guessing wrong strands the session (§9.4).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "prompt_versions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{prompt_name: version} pinned once at session start. §17.2 makes this the mechanism that stops a mid-meeting POI promotion from changing behaviour. Written by L-03.",
                    ),
                ),
                (
                    "evidence_manifest_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Half of the PROCESS idempotency key (§9.3)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company being onboarded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_sessions",
                        to="onboarding.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("APPROVED", "Approved")],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Requested depth, 1-5"
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                (
                    "source_chat_session_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Approval freezes the version; further edits create version+1 in DRAFT rather than mutating an approved set.",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Reusable for another company in the same tenant (D-05)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="onboarding.company",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("PREPARED", "Prepared"),
                            ("ADHOC", "Ad hoc"),
                            ("FOLLOWUP", "Follow-up"),
                        ],
                        default="PREPARED",
                        max_length=16,
                    ),
                ),
                (
                    "workflow_target",
                    models.CharField(
                        choices=[("WF1", "WF1"), ("WF2", "WF2"), ("WF3", "WF3")],
                        default="WF1",
                        max_length=8,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Join to FieldProvenance (B-05)",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("GREEN", "Green"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("sufficiency_score", models.FloatField(blank=True, null=True)),
                ("answer_summary", models.TextField(blank=True, default="")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{recording_id, t_start, t_end}] backing the score",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="onboarding_sessions.questionnaire",
                    ),
                ),
            ],
            options={
                "ordering": ["questionnaire_id", "order"],
            },
        ),
        migrations.AddField(
            model_name="onboardingsession",
            name="questionnaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_to_sessions",
                to="onboarding_sessions.questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="onboardingsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant (nullable for pre-tenant rows)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="questionnaire",
            index=models.Index(
                fields=["tenant", "status"], name="onboarding__tenant__3bd2f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["questionnaire", "status"],
                name="onboarding__questio_ef878a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingsession",
            index=models.Index(
                fields=["tenant", "status"], name="onboarding__tenant__2d95fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("COMPLETED", "ARCHIVED")), _negated=True
                ),
                fields=("company",),
                name="unique_active_session_per_company",
            ),
        ),
    ]
