# Generated by Django 4.2.16 on 2026-08-03 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0013_brandasset_ocr_confidence_brandasset_ocr_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("onboarding_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[("AUDIO", "Audio"), ("VIDEO", "Video")],
                        default="AUDIO",
                        help_text="AUDIO in v1; VIDEO reserved and unconstrained (§24)",
                        max_length=8,
                    ),
                ),
                (
                    "transcript_gcs_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "duration_s",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Whole seconds; null while still RECORDING",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECORDING", "Recording"),
                            ("UPLOADED", "Uploaded"),
                            ("TRANSCRIBED", "Transcribed"),
                            ("SUMMARIZED", "Summarized"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="RECORDING",
                        max_length=16,
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{text, key_moments: [{t, label}]} — written by a later story",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The uploaded audio, as a BrandAsset so it rides the existing ingestion pipeline. Null until the upload completes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_recordings",
                        to="onboarding.brandasset",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="onboarding__session_b75c79_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="onboarding__tenant__ee0319_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        help_text="The person consenting to be recorded", max_length=255
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("VERBAL_RECORDED", "Verbal, recorded"),
                            ("CHECKBOX", "Checkbox"),
                        ],
                        default="VERBAL_RECORDED",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What was consented to. No schema enforced here — the consent API story owns that contract.",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server-set (FR-REC-01); never accepted from a client",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on revocation. Visible to any consumer querying the session's consent state; triggers erasure in a later story, not this one.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The operator who captured the consent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "revoked_at"],
                        name="onboarding__session_4a57f1_idx",
                    )
                ],
            },
        ),
    ]
