# Generated by Django 4.2.16 on 2026-08-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onboarding", "0014_company_audience_languages_and_more"),
        ("onboarding_sessions", "0002_meetingrecording_consentrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="The Django model written to, e.g. 'Company'",
                        max_length=64,
                    ),
                ),
                ("field_name", models.CharField(max_length=128)),
                (
                    "extracted_value",
                    models.JSONField(
                        help_text="What the agent proposed, in the shape it will be written"
                    ),
                ),
                (
                    "final_value",
                    models.JSONField(
                        blank=True,
                        help_text="What a reviewer confirmed or edited it to; null until then",
                        null=True,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("KEY", "Key"), ("SECONDARY", "Secondary")],
                        default="SECONDARY",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="0.000-1.000, bounded by its own constraint. Null before scoring.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "source_span",
                    models.JSONField(
                        blank=True,
                        help_text="{recording_id, t_start, t_end} — the same shape as Question.evidence, so K-01 can seek a player from either.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("EDITED", "Edited"),
                            ("CONFLICT", "Conflict"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_provenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "source_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provenance",
                        to="onboarding.brandasset",
                    ),
                ),
                (
                    "source_recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provenance",
                        to="onboarding_sessions.meetingrecording",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["model_name", "field_name"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="onboarding__session_3d3d64_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="onboarding__tenant__6a0be9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fieldprovenance",
            constraint=models.UniqueConstraint(
                fields=("session", "model_name", "field_name"),
                name="unique_provenance_per_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldprovenance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("source_recording__isnull", False),
                    ("source_span__isnull", False),
                    ("source_media__isnull", False),
                    _connector="OR",
                ),
                name="provenance_requires_a_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldprovenance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="confidence_between_zero_and_one",
            ),
        ),
    ]
