# Generated by Django 4.2.16 on 2026-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding_sessions", "0003_fieldprovenance_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["status", "started_at"], name="onboarding__status_a1521c_idx"
            ),
        ),
    ]
