# Generated by Django 4.2.16 on 2026-08-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("onboarding_sessions", "0004_meetingrecording_onboarding__status_a1521c_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="As the operator typed it", max_length=255
                    ),
                ),
                (
                    "normalised_name",
                    models.CharField(
                        db_index=True,
                        help_text="Lower-cased, punctuation and legal suffixes stripped — the same normalisation the agent's Redis cache key uses, so the two layers agree on what counts as the same business",
                        max_length=255,
                    ),
                ),
                (
                    "brief",
                    models.JSONField(
                        help_text="The full BusinessResearchBrief payload"
                    ),
                ),
                (
                    "degraded",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when research could not run (AC-3)",
                    ),
                ),
                (
                    "degraded_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("fact_count", models.PositiveIntegerField(default=0)),
                ("unknown_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attached once a session exists; prep can precede one",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_briefs",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "normalised_name"],
                        name="onboarding__tenant__5d28bd_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="researchbrief",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("tenant", "normalised_name"),
                name="unique_brief_per_business_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchbrief",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("normalised_name",),
                name="unique_brief_per_business_without_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchbrief",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("degraded", False),
                    models.Q(("degraded_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="degraded_brief_states_its_reason",
            ),
        ),
    ]
