# Generated by Django 4.2.16 on 2026-08-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0014_company_audience_languages_and_more"),
        ("onboarding_sessions", "0005_researchbrief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable because preparation precedes onboarding. C-01 routes a prep turn with no session, C-02 stores a research brief keyed on a business name rather than a Company, and C-03 generates a questionnaire from that brief — none of which require the company to exist yet. Requiring it here would make the epic's normal path unstorable. Attached once a Company is created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="onboarding.company",
            ),
        ),
    ]
