# Generated by Django 4.2.16 on 2026-08-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding_sessions", "0006_alter_questionnaire_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                help_text="The version this one replaces (C-04 AC-3). Makes the chain explicit rather than implied by a version number: the card requires the approved version to survive intact, and the evidence spans on Question point at a specific version's rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="onboarding_sessions.questionnaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaire",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "DRAFT"),
                    ("company__isnull", False),
                    ("tenant__isnull", False),
                ),
                fields=("tenant", "company"),
                name="one_draft_questionnaire_per_company",
            ),
        ),
    ]
