# Generated by Django 4.2.16 on 2026-08-09 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onboarding_sessions", "0008_approved_questions_are_immutable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="The instant the meeting begins, in UTC"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(help_text="The instant it ends, in UTC"),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA zone the meeting was scheduled in, e.g. 'Europe/London'. Kept alongside the UTC instant so a rescheduled or recurring meeting lands at the same *local* time across a DST change.",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organiser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "starts_at"],
                        name="onboarding__tenant__cd30d6_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduledmeeting",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="meeting_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledmeeting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("timezone__regex", "^([A-Za-z_]+/[A-Za-z0-9_+\\-/]+|UTC)$")
                ),
                name="meeting_timezone_is_an_iana_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledmeeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("session",),
                name="one_scheduled_meeting_per_session",
            ),
        ),
    ]
