# Generated by Django 4.2.16 on 2026-08-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding_sessions", "0009_scheduledmeeting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmeeting",
            name="origin",
            field=models.CharField(
                choices=[
                    ("APP", "Created in the app"),
                    ("GOOGLE", "Created in Google Calendar"),
                ],
                db_index=True,
                default="APP",
                help_text="APP entries are editable here and pushed outward. GOOGLE entries are read-only here — the viewset refuses writes to them — because this app is not the system of record for somebody's own diary.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="scheduledmeeting",
            name="provider_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledmeeting",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="onboarding_sessions.onboardingsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledmeeting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id", ""), _negated=True),
                fields=("tenant", "provider_event_id"),
                name="one_meeting_per_provider_event",
            ),
        ),
    ]
