# Generated by Django 4.2.16 on 2026-08-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("onboarding_sessions", "0010_scheduledmeeting_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmeeting",
            name="provider_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CalendarSyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        choices=[
                            ("APP", "The in-app copy was kept"),
                            ("GOOGLE", "The Google copy was kept"),
                        ],
                        max_length=8,
                    ),
                ),
                ("discarded", models.JSONField(default=dict)),
                ("rule", models.CharField(blank=True, default="", max_length=255)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to="onboarding_sessions.scheduledmeeting",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-detected_at"],
                        name="onboarding__tenant__e3f4f6_idx",
                    )
                ],
            },
        ),
    ]
