# Generated by Django 4.2.16 on 2026-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0011_scheduledmeeting_provider_synced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrecording",
            name="finalise_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="upload_gcs_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="upload_session_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
