# Generated by Django 4.2.16 on 2026-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0012_meetingrecording_finalise_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrecording",
            name="transcript",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{text, speaker, t_start, t_end, redaction_applied}]",
            ),
        ),
    ]
