# Generated by Django 4.2.16 on 2026-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0013_add_transcript_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="process_job_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OIA job id from the most recent PROCESS dispatch",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="onboardingsession",
            name="process_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Terminal callback summary from OIA (§10.2.2)",
            ),
        ),
    ]
