# Generated by Django 4.2.16 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0014_add_process_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-session config (e.g. key_confirm_delegate for AC-4)",
            ),
        ),
    ]
