# Generated by Django 4.2.16 on 2026-09-02 00:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("onboarding_sessions", "0016_add_erasure_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="retentionconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("retention_days__gte", 1),
                    ("retention_days__lte", 3650),
                ),
                name="retention_days_range",
            ),
        ),
    ]
