# Generated by Django 4.2.16 on 2026-09-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("onboarding_sessions", "0017_add_retention_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        help_text="'operator' or 'participant'", max_length=50
                    ),
                ),
                ("mic_label", models.CharField(blank=True, default="", max_length=255)),
                ("stream_index", models.PositiveSmallIntegerField()),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendees",
                        to="onboarding_sessions.meetingrecording",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="onboarding_sessions.onboardingsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["stream_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="meetingattendee",
            constraint=models.UniqueConstraint(
                fields=("session", "stream_index"), name="unique_attendee_per_stream"
            ),
        ),
    ]
