# Generated by Django 4.2.16 on 2026-09-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0018_add_meeting_attendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrecording",
            name="stream_assets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{stream_index, gcs_path, session_url, brand_asset_id, speaker_name}] — empty for single-mic recordings",
            ),
        ),
    ]
