# Generated by Django 4.2.16 on 2026-09-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0019_meetingrecording_stream_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrecording",
            name="transcript",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{text, speaker, speaker_name, t_start, t_end, redaction_applied}] — speaker_name is null for single-mic recordings, which have no mic-to-attendee map to resolve",
            ),
        ),
    ]
