# Generated by Django 4.2.16 on 2026-09-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0019_meetingrecording_stream_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrecording",
            name="transcript",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{text, speaker, speaker_name, speaker_role, t_start, t_end, redaction_applied}] — both speaker fields are null for single-mic recordings, which have no mic-to-attendee map. speaker_name is the legal record; speaker_role is what model prompts are attributed by, so no name is sent to a provider",
            ),
        ),
    ]
