# Generated by Django 4.2.16 on 2026-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_sessions", "0020_alter_meetingrecording_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrecording",
            name="transcript_complete",
            field=models.BooleanField(
                blank=True,
                help_text="#662 · whether the live transcript covers the whole recording. NULL means never assessed — every row finalised before truncation was detectable is in that state, and claiming those are complete would be asserting something we cannot know.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meetingrecording",
            name="transcript_missing_s",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="#662 · whole seconds of recording the transcript does not cover; NULL when never assessed, 0 when complete",
                null=True,
            ),
        ),
    ]
