# Generated by Django 4.2.16 on 2026-02-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_add_unique_brand_asset_constraint"),
        ("ai_services", "0003_migrate_messages_to_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="ai_services_session_1fa282_idx",
            old_name="ai_services__session_created_idx",
        ),
        migrations.AddField(
            model_name="sessionattachment",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_attachments",
                to="onboarding.brandasset",
            ),
        ),
        migrations.AddField(
            model_name="sessionattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="ai_services.chatmessage",
            ),
        ),
    ]
