# Generated by Django 4.2.16 on 2026-02-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_add_sessionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattachment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_services.chatsession'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_services.chatmessage'),
        ),
    ]
