# Generated by Django 4.2.16 on 2026-02-24 17:39

from django.db import migrations, models
import django.db.models.deletion


def backfill_session_from_message(apps, schema_editor):
    """Populate session FK from message.session for existing attachments."""
    SessionAttachment = apps.get_model("ai_services", "SessionAttachment")
    for att in SessionAttachment.objects.filter(
        session__isnull=True, message__isnull=False
    ).select_related("message"):
        att.session = att.message.session
        att.save(update_fields=["session"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_add_sessionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattachment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_services.chatsession'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_services.chatmessage'),
        ),
        migrations.RunPython(
            backfill_session_from_message,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
