# Generated by Django 4.2.16 on 2026-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0005_attachment_nullable_message_add_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-is_pinned", "-last_activity"],
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
