# Generated by Django 4.2.16 on 2026-03-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orchestration", "0004_trendnotification"),
        ("tenants", "0008_add_vertex_ai_data_store_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "layout_data",
                    models.JSONField(
                        default=dict,
                        help_text="React Flow positions: {nodes: {id: {x, y}}, viewport: {x, y, zoom}}",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("cloned", "Cloned"),
                            ("template", "Template"),
                            ("chat", "From Chat"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_workflows",
                        to="orchestration.pipelinemanifest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_workflows",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "manifest_snapshot",
                    models.JSONField(
                        help_text="Frozen manifest_data at execution time"
                    ),
                ),
                (
                    "layout_snapshot",
                    models.JSONField(help_text="Frozen layout_data at execution time"),
                ),
                (
                    "summary",
                    models.JSONField(default=dict, help_text="Executive summary text"),
                ),
                (
                    "dashboard_data",
                    models.JSONField(
                        default=dict,
                        help_text="Hybrid KPI data: {typed: {voc_health_score, nps, ...}, generic: {k: v}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_snapshot",
                        to="orchestration.analysisjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_snapshots",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="workspace.userworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatWorkspaceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_session_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_link",
                        to="orchestration.analysisjob",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workspace.workflowsnapshot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_chat_links",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_links",
                        to="workspace.userworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userworkflow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "name"),
                name="unique_active_workflow_name_per_tenant",
            ),
        ),
    ]
