# Generated by Django 4.2.16 on 2026-02-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisjob",
            name="manifest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="orchestration.pipelinemanifest",
            ),
        ),
    ]
