# Generated by Django 4.2.16 on 2026-03-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_add_vertex_ai_data_store_field"),
        ("orchestration", "0002_make_manifest_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'acme-corp')",
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "competitor_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Competitor"),
                            ("indirect", "Indirect Competitor"),
                            ("emerging", "Emerging Competitor"),
                            ("substitute", "Substitute"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this competitor was first identified",
                        null=True,
                    ),
                ),
                (
                    "last_profiled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a full profile scan was run",
                        null=True,
                    ),
                ),
                ("profile_version", models.PositiveIntegerField(default=1)),
                (
                    "profile_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full competitor profile data from CIA",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_profiles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(help_text="Date this snapshot represents"),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        default=dict, help_text="Full profile data at time of snapshot"
                    ),
                ),
                (
                    "changes_detected",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changes vs. previous snapshot",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="orchestration.competitorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_snapshots",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="competitorsnapshot",
            constraint=models.UniqueConstraint(
                fields=("competitor", "snapshot_date"), name="unique_snapshot_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitorprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_competitor_per_tenant"
            ),
        ),
    ]
